export enum Position {
  INTERN = 'INTERN',
  JUNIOR_SALES_EXECUTIVE = 'JUNIOR SALES EXECUTIVE',
  SENIOR_SALES_EXECUTIVE = 'SENIOR SALES EXECUTIVE',
  ASSISTANT_SALES_MANAGER = 'ASSISTANT SALES MANAGER',
  SALES_MANAGER_INBOUND = 'SALES MANAGER_INBOUND',
  RESERVATION_EXECUTIVE = 'RESERVATION EXECUTIVE',
  SENIOR_RESERVATION_EXECUTIVE = 'SENIOR RESERVATION EXECUTIVE'

}
